import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Footer from "../Components/Footer";
import Header from "../Components/Header";
import styles from "../styles/Home.module.css";
import Blog from "../Components/Blog";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="App">      
        <Blog />       
      </main>
    </div>
  );
};

export default Home;
